name: sesimiduy
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  easy_localization: ^3.0.1
  kartal: ^2.8.0
  responsive_framework: ^0.2.0
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.5.0
  firebase_database: ^10.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
